---
- name: Get kernel version
  command: uname --kernel-release
  register: kernelrelease
  changed_when: False
  tags: gps

- name: install required packages
  apt:
    name:
      [
        "python3-pip",
        "gpsd",
        "gpsd-clients",
        "chrony",
        "pps-tools",
        "linux-headers-{{ kernelrelease.stdout.strip() }}",
        "dkms",
      ]
    state: present
    update_cache: yes
  tags: gps

- name: install python ubxserial modules
  pip:
    name: ubxserial

- name: configure chrony and gpsd (not active)
  template:
    src: "{{ item }}"
    dest: "/etc/shepherd/"
    mode: 0644
  with_items:
    - chrony.conf
    - gpsd.conf
    - ublox_config.ubx  # TODO: this file seems still unused
  tags:
    - gps
    - conf

- name: Disable factory enabled capes
  lineinfile:
    dest: '/boot/uEnv.txt'
    regexp: "{{ item.regexpress }}"
    line: "{{ item.replacement }}"
    state: present
  with_items:
    - {
      regexpress: "#?disable_uboot_overlay_video=.*$",
      replacement: "disable_uboot_overlay_video=1",
      }
    - {
      regexpress: "#?disable_uboot_overlay_audio=.*$",
      replacement: "disable_uboot_overlay_audio=1",
      }
    - {
      regexpress: "#?disable_uboot_overlay_wireless=.*$",
      replacement: "disable_uboot_overlay_wireless=1",
      }
    - {
      regexpress: "#?disable_uboot_overlay_adc=.*$",
      replacement: "disable_uboot_overlay_adc=1",
      }
    - {
      regexpress: "#?enable_uboot_cape_universal=.*$",
      replacement: "#enable_uboot_cape_universal=1",
      }
  notify: restart device
  tags: gps

- name: Set enabled capes
  lineinfile:
    dest: '/boot/uEnv.txt'
    regexp: '#?uboot_overlay_addr6=.*$'
    line: "uboot_overlay_addr6=/lib/firmware/BB-GPS-00A0.dtbo"
    state: present
  notify: restart device
  tags: gps

- name: Copy pps-gmtimer code
  synchronize:
    src: "{{ pps_gmtimer_path }}"
    dest: /opt/pps-gmtimer
  tags:
    - gps
    - pps

- name: Build and install pps-gmtimer module
  make:
    chdir: /opt/pps-gmtimer
    target: install
  tags:
    - gps
    - pps

- name: Copy device tree overlay for GPS-Capelet
  synchronize:
    src: "{{ gps_overlay_path }}"
    dest: "/opt/gps-overlay"
  tags:
    - gps
    - pps

- name: Build and install GPS device tree overlay
  make:
    chdir: "/opt/gps-overlay"
    target: install
  notify: restart device
  tags:
    - gps
    - device-tree

- name: Add udev rule for hw pps device
  copy:
    src: "91-hw-pps.rules"
    dest: "/etc/udev/rules.d/"
  tags:
    - gps
    - conf

- name: make system find kernel-module
  command: depmod -ae
  tags:
    - gps
    - conf

- include_tasks: systemd.yml
  tags:
    - gps
    - conf
    - systemd
