---
- name: Prepare paths for service override
  file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    state: directory
    recurse: yes
  with_items:
    - gpsd
    - chrony

- name: Override service configs
  copy:
    src: "{{ item }}.override.conf"
    dest: "/etc/systemd/system/{{ item }}.service.d/"
  with_items:
    - chrony
    - gpsd

- name: Add ublox-config systemd service
  template:
    src: "ublox_config.service"
    dest: "/etc/systemd/system/"

- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: yes  # services may not exist
  with_items:
    - gpsd.socket
    - gpsd.service
    - chrony.service
    - ublox_config.service

- name: Disable connman automatic time update
  shell: busctl --system call net.connman / net.connman.Clock SetProperty sv "TimeUpdates" s "manual"
  tags:
    - conf
    - systemd
