language: python
python:
  - "3.6"
# TODO: is this file outdates without debian-packages? same with build.sh?

services:
  - docker

addons:
  apt:
    packages:
     - sshpass

script:
 - export PROJECT_DIR=$PWD
 - docker build -t shepherd-builder-img .
 - docker create -it --name shepherd-builder shepherd-builder-img
 - docker cp $PROJECT_DIR/software shepherd-builder:/code
 - docker start -a shepherd-builder
 - docker cp shepherd-builder:/artifacts $PROJECT_DIR/

before_deploy:
 - cd $PROJECT_DIR/software/shepherd-herd

deploy:

 - provider: script
   script: SSHPASS=$DEPLOY_PASS sshpass -e scp -v -o StrictHostKeyChecking=no $PROJECT_DIR/artifacts/debian/* $DEPLOY_USER@$DEPLOY_HOST:shepherd/debian/
   skip_cleanup: true

 - provider: pypi
   user: $PYPI_USER
   password: $PYPI_PASS
   on:
     tags: true
     branch: master
