- name: Disable GPS and PTP services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  with_items:
    - chrony.service
    - gpsd.service
    - gpsd.socket
    - phc2sys.service # TODO: these fail in recent ubuntu nightlies, linuxptp switched to servive-templates, keep old style for now
    - ptp4l.service
    - phc2sys@eth0.service
    - ptp4l@eth0.service
  ignore_errors: yes  # services may not exist
  tags:
    - ptp
    - conf

- name: Enable NTP service
  systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: yes
    daemon_reload: yes
  tags:
    - ptp
    - conf
