---
- name: Disable most factory enabled capes and overlays
  lineinfile:
    dest: "/boot/uEnv.txt"
    regexp: "{{ item.regexpress }}"
    line: "{{ item.replacement }}"
    state: present
  with_items:
    - {
        regexpress: "#?disable_uboot_overlay_video=.*$",
        replacement: "disable_uboot_overlay_video=1",
      }
    - {
        regexpress: "#?disable_uboot_overlay_audio=.*$",
        replacement: "disable_uboot_overlay_audio=1",
      }
    - {
        regexpress: "#?disable_uboot_overlay_wireless=.*$",
        replacement: "disable_uboot_overlay_wireless=1",
      }
    - {
        regexpress: "#?disable_uboot_overlay_adc=.*$",
        replacement: "disable_uboot_overlay_adc=1",
      }
    - {
        regexpress: "#?enable_uboot_cape_universal=.*$",
        replacement: "#enable_uboot_cape_universal=1",
      }
  become: yes
  notify:
    - restart device
  tags:
    - device-tree

- name: Enable shepherd overlays
  lineinfile:
    dest: "/boot/uEnv.txt"
    regexp: "{{ item.regexpress }}"
    line: "{{ item.replacement }}"
    state: present
  with_items:
    - {
      regexpress: "#?enable_uboot_overlays=.*$"
        replacement: "enable_uboot_overlays=1", }
    - {
      regexpress: '#?uboot_overlay_pru=.*$',
      replacement: "uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-19-TI-00A0.dtbo",
      } # TODO: this _overlay_pru should maybe be _overlay_addr0? it is not listed in recent uEnvs
    - {
      regexpress: '#?dtb_overlay=.*$',
      replacement: "dtb_overlay=/lib/firmware/BB-SHPRD-00A0.dtbo",
      }
    - {
      regexpress: '#?uboot_overlay_addr4=.*$',
      replacement: "#uboot_overlay_addr4=/lib/firmware/BB-I2C1-00A0.dtbo",
      }
    - {
      regexpress: '#?uboot_overlay_addr5=.*$',
      replacement: "uboot_overlay_addr5=/lib/firmware/BB-UART1-00A0.dtbo",
      }
  become: yes
  notify:
    - restart device
  tags:
    - device-tree

- name: Get kernel version
  command: uname --kernel-release
  register: kernelrelease
  changed_when: False

- name: Install required packages
  apt:
    name:
      [
        "linux-headers-{{ kernelrelease.stdout.strip() }}",
        "linux-firmware",
        "zlib1g-dev",
        "libjpeg-dev",
        "python3-numpy",    # TODO: rethink apt usage. most of these are easier updatable per pip
        "python3-scipy",
        "python3-zmq",
        "python3-gevent",
        "python3-h5py",
        "python3-pip",
        "python3-setuptools",
        "python3-virtualenv",
        "python3-msgpack-numpy",
        "libdbus-glib-1-dev",
        "libgirepository1.0-dev",
        "dkms",
      ]
    state: present
    update_cache: yes

- name: Get full path of repository
  local_action: "shell realpath {{ role_path }}/../../.."
  register: repo_dir
  become: no
  tags:
    - source-code
    - device-tree
    - python
    - systemd

- name: Create paths for shepherd
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - "{{ shepherd_install_path }}"
    - "{{ shepherd_data_path }}"
    - "{{ shepherd_config_path }}"
  tags:
    - source-code
    - python

- name: Synchronize host shepherd dir to target
  synchronize:
    src: "{{ repo_dir.stdout }}/"
    dest: "{{ shepherd_install_path }}"
    delete: yes
    owner: no
    group: no
    rsync_opts:
      - "--exclude=.eggs"
      - "--exclude=__pycache__"
  tags:
    - source-code
    - python

- name: own shepherd codebase
  command: 'chown -R {{ ansible_user }} {{ shepherd_install_path }}'
  become: true
  tags:
    - source-code
    - python

- name: Install shepherd python package
  command: python3 setup.py install --force
  args:
    chdir: "{{ shepherd_install_path }}/software/python-package"
  tags:
    - install
    - python

- name: Deploy example configuration
  template:
    src: "{{ repo_dir.stdout }}/software/python-package/{{ item }}"
    dest: "{{ shepherd_config_path }}"
    force: no
    owner: "{{ ansible_user }}"
  with_items:
   - 'example_config_emulator.yml'
   - 'example_config_harvester.yml'
  tags:
    - source-code
    - python
    - conf

- name: set default configuration to harvest (mainly for launcher)
  template:
    src: "{{ repo_dir.stdout }}/software/python-package/example_config_harvester.yml"
    dest: "{{ shepherd_config_path }}/config.yml"
    force: no
    owner: "{{ ansible_user }}"
  tags:
    - source-code
    - python
    - conf

- name: Link to shepherd-sheep for compatibility with deb package
  file:
    src: /usr/local/bin/shepherd-sheep
    dest: /usr/bin/shepherd-sheep
    state: link
  tags:
    - install
    - python

- include_tasks: build.yml
  tags:
    - install
    - build

- include_tasks: systemd.yml
  tags:
    - install
    - systemd

# TODO: divide better into parts, so rebuild_fw triggers a reload of kernel module as well, but not the make-permanent-part
- name: Make Shepherd Module permanent
  lineinfile:
    dest: "/etc/modules"
    regexp: "#?shepherd.*$"
    line: "shepherd"
    state: present
