---
- name: Add systemd unit
  copy:
    src: '{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
  with_items:
   - shepherd.service
   - shepherd-rpc.service
   - shepherd-launcher.service
  tags:
    - install
    - systemd

- name: Configure systemd services
  systemd:
    name: '{{ item.name }}'
    state: stopped
    enabled: '{{ item.enabled }}'
    daemon_reload: yes
  with_items:
   - { name: shepherd, enabled: no}
   - { name: shepherd-rpc, enabled: no}
   - { name: shepherd-launcher, enabled: yes}
   - { name: systemd-timesyncd, enabled: no}
  tags:
    - conf
    - systemd

- name: Disable connman automatic time update
  shell: busctl --system call net.connman / net.connman.Clock SetProperty sv "TimeUpdates" s "manual"
  tags:
    - conf
    - systemd

