---
- name: Configure PTP for slave-only mode
  lineinfile:
    dest: "/etc/linuxptp/ptp4l.conf"
    regexp: "slaveOnly.*$"
    line: "slaveOnly  1"
    state: present
  tags:
    - ptp
    - conf

- name: Disable GPS and NTP services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  with_items:
    - chrony.service
    - gpsd.service
    - gpsd.socket
    - systemd-timesyncd.service
  ignore_errors: yes  # services may not exist
  tags:
    - ptp
    - conf

- name: Enable ptp services
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items:
    - phc2sys.service # TODO: these fail in recent ubuntu nightlies, linuxptp switched to servive-templates, keep old style for now
    - ptp4l.service
    - phc2sys@eth0.service
    - ptp4l@eth0.service
  ignore_errors: yes  # services may not exist
  tags:
    - ptp
    - conf
